### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by tmurphy54** [divinity76/YurOTS#3]
Hello I dabbled with OTs over 14 years ago, I finally found the files I'm familiar with.  However I have no idea what Gitignore is.  I'm trying to find the yurots.exe in the OTS folder and long story short I think it's being hidden with gitignore?  What are my steps to find the yurots.exe to start the server?

**Comment by divinity76** [comment]
good old days.

unfortunately YurOTS.exe is not part of this repo *at all*, it only contains the source code that can be used to create YurOTS.exe with a C++ compiler. 

you can download YurOTS.exe here: https://web.archive.org/web/20070119031404/http://yurez.ovh.org/ots/YurOTS_094f.rar

.gitignore has nothing to do with which files you can see, it only put restrictions on what the program "git" can see, if you are not using "git", the .gitignore file does absolutely nothing for you ^^

unfortunately i don't have time to help you out much, i'm rather over-worked and exhausted these days
